markdown: redcarpet
highlighter: null
permalink: /:title

# Site settings
title: Code Brownie
#email: your-email@domain.com
description: "The blog and personal site of Matt 'Brownie' Brown"
baseurl: ""
url: "http://codebrownie.com"
github: "mattbrown"
twitter: "bionicseraph"

# Build settings
markdown: kramdown
permalink: pretty
redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed